disabled_rules:
  - line_length
  - identifier_name
  - nesting  # Allow deeply nested enums for namespacing
  - redundant_discardable_let  # Preserve 'let _ =' in result builder contexts (required for Swift 6.0+)
  - opening_brace  # Handled by swift-format
  - trailing_comma  # Handled by swift-format
  - trailing_whitespace  # Preserve whitespace in snapshot tests
  - orphaned_doc_comment  # Allow module-level documentation
  - large_tuple  # CSS/HTML properties may require tuples with multiple components
  - mark  # Allow flexible MARK comment formatting
  - redundant_string_enum_value  # Explicit enum values improve clarity for CSS/HTML keywords

opt_in_rules:
  - empty_count
  - explicit_init
  - sorted_imports
  - force_cast
  - force_try
  - closure_spacing
  - operator_usage_whitespace
  - private_outlet
  - redundant_nil_coalescing
  - literal_expression_end_indentation
  - single_test_class
  - sorted_first_last
  - vertical_whitespace
  - legacy_random
  - no_extension_access_modifier
  - colon
  
included:
  - Package.swift
  - Sources
  - Tests

excluded:
  - Carthage
  - Pods
  - fastlane
  - build

analyzer_rules:
  - unused_import

colon:
  apply_to_dictionaries: true

vertical_whitespace:
  max_empty_lines: 1

# Increased length limits for test files with extensive snapshots
type_body_length:
  warning: 800
  error: 900

file_length:
  warning: 900
  error: 1000

function_body_length:
  warning: 270
  error: 300

# Allow short type names for HTML/CSS elements (H1, BR, B, RGB, HSL, etc.)
type_name:
  min_length:
    warning: 1
    error: 0
  max_length:
    warning: 40
    error: 50

# Allow more function parameters for HTML/CSS functions with many attributes
function_parameter_count:
  warning: 8
  error: 10

# Increased cyclomatic complexity for CSS/HTML property parsing functions
cyclomatic_complexity:
  warning: 16
  error: 20
